# Generated by Django 3.2.13 on 2022-04-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_city', models.CharField(max_length=50, null=True)),
                ('customer_state', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'DIM_CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='DimProduct',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_cat_name_pt', models.CharField(max_length=100, null=True)),
                ('product_cat_name_en', models.CharField(max_length=100, null=True)),
                ('product_weight_g', models.IntegerField(null=True)),
                ('product_length_cm', models.IntegerField(null=True)),
                ('product_height_cm', models.IntegerField(null=True)),
                ('product_width_cm', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'DIM_PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='DimSeller',
            fields=[
                ('seller_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seller_city', models.CharField(max_length=50, null=True)),
                ('seller_state', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'DIM_SELLER',
            },
        ),
        migrations.CreateModel(
            name='FactDeliveredOrders',
            fields=[
                ('unique_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_day_id', models.DateField(null=True)),
                ('nr_of_orders', models.IntegerField(null=True)),
                ('nr_of_products', models.IntegerField(null=True)),
                ('product_sales_revenue', models.FloatField(null=True)),
                ('shipping_revenue', models.FloatField(null=True)),
                ('nr_of_review_score', models.IntegerField(null=True)),
                ('sum_review_score', models.IntegerField(null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_mart.dimcustomer')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_mart.dimproduct')),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_mart.dimseller')),
            ],
            options={
                'db_table': 'FACT_DELIVERED_ORDERS',
            },
        ),
    ]
