# Generated by Django 3.2.13 on 2022-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimcustomer',
            name='customer_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimcustomer',
            name='customer_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dimcustomer',
            name='customer_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimproduct',
            name='product_height_cm',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dimproduct',
            name='product_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dimproduct',
            name='product_length_cm',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dimproduct',
            name='product_weight_g',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dimproduct',
            name='product_width_cm',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dimseller',
            name='seller_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimseller',
            name='seller_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dimseller',
            name='seller_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factdeliveredorders',
            name='product_sales_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='factdeliveredorders',
            name='shipping_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
