# Generated by Django 3.2.13 on 2022-04-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('customer_unique_id', models.CharField(max_length=32)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Geolocations',
            fields=[
                ('zip_code_prefix', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('city', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'geolocations',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryNameTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=200)),
                ('product_category_name_english', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product_category_name_translation',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=100)),
                ('product_name_length', models.DecimalField(decimal_places=6, max_digits=12)),
                ('product_description_length', models.DecimalField(decimal_places=6, max_digits=12)),
                ('product_photos_qty', models.DecimalField(decimal_places=6, max_digits=12)),
                ('product_weight_g', models.DecimalField(decimal_places=6, max_digits=12)),
                ('product_length_cm', models.DecimalField(decimal_places=6, max_digits=12)),
                ('product_height_cm', models.DecimalField(decimal_places=6, max_digits=12)),
                ('product_width_cm', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('seller_zip_code_prefix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.geolocations')),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=30)),
                ('order_purchase_timestamp', models.DateTimeField()),
                ('order_approved_at', models.DateTimeField()),
                ('order_delivered_carrier_date', models.DateTimeField()),
                ('order_delivered_customer_date', models.DateTimeField()),
                ('order_estimated_delivery_date', models.DateTimeField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.customers')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderReviews',
            fields=[
                ('review_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('review_score', models.IntegerField()),
                ('review_comment_title', models.CharField(max_length=200)),
                ('review_comment_message', models.CharField(max_length=300)),
                ('review_creation_date', models.DateTimeField()),
                ('review_answer_timestamp', models.DateTimeField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.orders')),
            ],
            options={
                'db_table': 'order_reviews',
            },
        ),
        migrations.CreateModel(
            name='OrderPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sequential', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_installments', models.IntegerField()),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.orders')),
            ],
            options={
                'db_table': 'order_payments',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.CharField(max_length=32)),
                ('shipping_limit_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('freight_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.orders')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.products')),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.sellers')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_zip_code_prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_olist_data.geolocations'),
        ),
    ]
