# Generated by Django 3.2.13 on 2022-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_olist_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreviews',
            name='review_comment_message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderreviews',
            name='review_comment_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
