# Generated by Django 3.2.13 on 2022-04-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_olist_data', '0002_auto_20220421_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='shipping_limit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderreviews',
            name='review_answer_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderreviews',
            name='review_creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_delivered_carrier_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_delivered_customer_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_estimated_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_purchase_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='productcategorynametranslation',
            table=None,
        ),
    ]
