# Generated by Django 3.2.13 on 2022-04-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_olist_data', '0004_auto_20220426_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreviews',
            name='review_comment_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderreviews',
            name='review_comment_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcategorynametranslation',
            name='product_category_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategorynametranslation',
            name='product_category_name_english',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description_length',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12),
        ),
    ]
